default_context:
  name: "{{ cookiecutter.name }}"
  version: "{{ cookiecutter.version }}"
  slug: "{{ cookiecutter.slug }}"
  command: "{{ cookiecutter.command }}"
  cli: "{{ cookiecutter.cli }}"
  config: "{{ cookiecutter.config }}"
  compat: "{{ cookiecutter.compat }}"
  jupyter: "{{ cookiecutter.jupyter }}"
  sqlite: "{{ cookiecutter.sqlite }}"
  pypy: "{{ cookiecutter.pypy }}"
  description: "{{ cookiecutter.description }}"
  author: "{{ cookiecutter.author }}"
  email: "{{ cookiecutter.email }}"
  keywords: "{{ cookiecutter.keywords }}"
  license: "{{ cookiecutter.license }}"
  repo_service: "{{ cookiecutter.repo_service }}"
  repo_service_username: "{{ cookiecutter.repo_service_username }}"
  repo_service_reponame: "{{ cookiecutter.repo_service_reponame }}"
  docker_service_username: "{{ cookiecutter.docker_service_username }}"
  docker_service_reponame: "{{ cookiecutter.docker_service_reponame }}"
  github_action: "{{ cookiecutter.github_action }}"
  ml: "{{ cookiecutter.ml }}"
  editor: "{{ cookiecutter.editor }}"
  url: "{{ cookiecutter.url }}"