name: Docker

on: [push, pull_request]

env:
  ENVIRONMENT: test
  VERBOSE: true
  TERM: xterm
  
  GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: {% raw %}${{ github.actor }}{% endraw %}
  PROJECT: {% raw %}${{ github.event.repository.name }}{% endraw %}

jobs:
  build-docker:
    name: Build and Push
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - name: Login to Registry
        run: |
          echo $GITHUB_TOKEN | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin
      - name: Pull latest image
        run: |
          make docker-pull
      - name: Build Image
        run: |
          export DOCKER_TAG=${GITHUB_REF##*/}
          make docker-build
      - name: Push Image
        run: |
          make docker-push
{% if cookiecutter.singularity == "y" %}
  build-singularity:
    needs:
      - build-docker

    name: Build Singularity
    runs-on: ubuntu-latest

    container:
      image: quay.io/singularity/docker2singularity
      options: --privileged
    
    steps:
      - name: Build SIF File
        run: |
          DOCKER_IMAGE="${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${PROJECT}"
          SINGULARITY_IMAGE="$(echo -n ${DOCKER_IMAGE} | tr -c '[:alnum:].' '-').sif"

          docker-entrypoint.sh /docker2singularity.sh \
            --name ${SINGULARITY_IMAGE} \
             ${DOCKER_IMAGE}

          echo ${GITHUB_TOKEN} | singularity remote login -u ${DOCKER_USERNAME} --password-stdin oras://${DOCKER_REGISTRY}
          singularity push /output/${SINGULARITY_IMAGE} oras://${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${PROJECT}:singularity
{% endif %}