name: Jobs

on:
  push:
    branches:
      - master

env:
  COVERALLS_REPO_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}

  ENVIRONMENT: test
  VERBOSE: true
  TERM: xterm

  {{ cookiecutter.slug.upper() }}_JOBS_GITHUB_USERNAME: {{ cookiecutter.repo_service_username }}
  {{ cookiecutter.slug.upper() }}_JOBS_GITHUB_OAUTH_TOKEN: {% raw %}${{ secrets.{% endraw %}{{ cookiecutter.slug.upper() }}_JOBS_GITHUB_OAUTH_TOKEN }}

jobs:
  jobs:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - uses: actions/setup-python@v2
        name: Set up Python 3.9
        with:
          python-version: 3.9
      - name: Upgrade PIP and packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: |
          pip install -r requirements-jobs.txt
          python setup.py develop
      - name: Run Jobs
        run: |
          bpyutils --run-jobs {{ cookiecutter.slug }}.jobs