name: Model CI

on: [push, pull_request]

env:
  PIP_USE_DEPRECATED: "legacy-resolver"

jobs:
  train:
    name: Train
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/achillesrasquinha/dl

    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          python setup.py develop
      - name: Run Pipeline
        run: |
          bpyutils -m {{ cookiecutter.slug }}.data.get_data
          bpyutils -m {{ cookiecutter.slug }}.data.preprocess_data
          bpyutils -m {{ cookiecutter.slug }}.pipelines.train