language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - make VENVDIR=$VIRTUAL_ENV VERBOSE=true

script:
  - make test VENVDIR=$VIRTUAL_ENV VERBOSE=true

after_success:
  - make coverage ENVIRONMENT=test VENVDIR=$VIRTUAL_ENV VERBOSE=true